[RFC] Coverity fixes
delftswa2017/neovim pull request #4
Opened 2017-03-11 18:19 UTC by sander2

Some coverity fixes. Since these bugs were known, this is a case of technical debt.

2017-03-11 21:18 UTC, Hjdskes requested changes
Nice work!! Just two minor style fixes and a question :)

2017-03-11 21:18 UTC, Hjdskes commented on src/nvim/getchar.c
> +                if (typebuf.tb_maplen > 0)
Style: needs braces

2017-03-11 21:18 UTC, Hjdskes commented on src/nvim/getchar.c
> +                  typebuf.tb_off];
Style?

2017-03-11 21:18 UTC, Hjdskes commented on src/nvim/option.c
> +              } else if (!(options[opt_idx].flags & P_NO_DEF_EXP)) {
Are we sure this is the correct behaviour?

2017-03-12 11:10 UTC, sander2 commented on src/nvim/option.c
> +              } else if (!(options[opt_idx].flags & P_NO_DEF_EXP)) {
Pretty sure, since (1) this is how flags are generally used, (2) this is how flags are used in the rest of the file.

2017-03-12 11:25 UTC, Hjdskes approved these changes

2017-03-12 13:19 UTC, sander2 commented
Squashed the last commit.

2017-03-12 13:22 UTC, Hjdskes commented
LGTM, merging.

2017-03-12 13:22 UTC, merged